"""Golden parity tests for the Python name-encoding port.

Expected values were generated by running the ORIGINAL TypeScript logic
(claudeService.ts encodeNames/decodeNames) in Node. If these fail, the Python
port has drifted from the client and real names risk leaking to the AI provider.
Do NOT edit expected values to make tests pass — fix name_encoding.py.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.name_encoding import (  # noqa: E402
    NameMapping, encode_names, decode_names, generate_ai_alias, build_name_mappings, ALIAS_POOL,
)

M = [
    NameMapping("章哲睿", "王坤鹏"),
    NameMapping("李明", "张三丰"),
    NameMapping("王刚", "欧阳"),
    NameMapping("周", "赵"),  # single-char surname & alias — never given-name encoded
]

# (input, expected_encoded) — golden from the TS implementation.
ENCODE_CASES = [
    ("章哲睿今天状态好，哲睿完成了文综。", "王坤鹏今天状态好，坤鹏完成了文综。"),
    ("李明和章哲睿一起讨论，明和睿都在。", "张三丰和王坤鹏一起讨论，三丰和睿都在。"),
    ("王刚提交了，刚很积极。", "欧阳提交了，阳很积极。"),
    ("周同学来了。", "赵同学来了。"),
    ("无人名的普通句子。", "无人名的普通句子。"),
    ("章哲睿、李明、王刚、周四人同时出现。哲睿、明、刚。",
     "王坤鹏、张三丰、欧阳、赵四人同时出现。坤鹏、三丰、阳。"),
]


def test_encode_matches_golden():
    for text, expected in ENCODE_CASES:
        assert encode_names(text, M) == expected, f"encode drift on: {text}"


def test_roundtrip_restores_original():
    for text, _ in ENCODE_CASES:
        assert decode_names(encode_names(text, M), M) == text, f"roundtrip drift on: {text}"


def test_empty_and_none_safe():
    assert encode_names("", M) == ""
    assert decode_names("", M) == ""


def test_no_mappings_is_identity():
    assert encode_names("章哲睿来了", []) == "章哲睿来了"
    assert decode_names("王坤鹏来了", []) == "王坤鹏来了"


def test_build_name_mappings_skips_students_without_alias():
    class Stub:
        def __init__(self, name, alias):
            self.name = name
            self.ai_alias = alias

    students = [Stub("章哲睿", "王坤鹏"), Stub("李明", None), Stub("王刚", "  欧阳  ")]
    mappings = build_name_mappings(students)
    assert len(mappings) == 2
    assert NameMapping("章哲睿", "王坤鹏") in mappings
    assert NameMapping("王刚", "欧阳") in mappings  # trimmed


def test_generate_ai_alias_avoids_existing():
    existing = ALIAS_POOL[:-1]  # everything except the last
    assert generate_ai_alias(existing) == ALIAS_POOL[-1]


def test_generate_ai_alias_falls_back_when_pool_exhausted():
    alias = generate_ai_alias(ALIAS_POOL)  # all taken
    assert alias in ALIAS_POOL
